apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNakE0TURZeApNVFEwTXpWYUZ3MDBNakE0TURZeE1UUTBNelZhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEUmVyU0tMdXdVdTVyZ3BjSnF5S3hhRTV0TEh1T0Fpc0RiWnliSFZrbjdMUlRhOUJaaApEajZCMEN5Y0RFQjlLNkM1bDRNcGN0bjFaUjdMem1iZ29iaG92ZDA3TWRhdUxRU2w3VXduaDUxbVRkL2dzNDc0Ckt1Y2FoVHpRd3g1N0xERzJ6dUsvYlVuUjhqdUM4VjhMMG9iNThaYXdMSXE0Z3N2TXp3dGxVNU56NWZva0xVOHMKOEdkWFQxc1N1cFNUc1ArTE5DNlVxaW9SYnE2cGQybHN5R1duZjM3alJCcjMwTDZYb0RpSkhMM1JrUDR4U2R2bApPZGlGb2ZINjJEMlN6SUlEUkZQSllidTZhdmRrYUJJVlFFWUFQSE5WZERkdDIzUExsS0Zmemp5ZEtqSE5VVW9sCkgyUlFSOTk4Ynd6M3NNNDU5Qkw3aDVGdVI1S0RFcnZwQmtpZkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlN4Q2JRWjUzZjdxMlNLbk56WgowNnNvQlRnUDhUQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUEwTmk4RU5SdDMySzQrUTZsQlkyZ1phY2dKSjBUCmFKbENFWjJ6b21HZG9MdkVzT015N1Z3cVhjQ0I4bWpxWVBqNjV0YnA1bERaTFh1UjM4YnlpdUFqbURZU0pIeDkKRHYzSUtPTVRtRWZIZUpLdDFLS1hjM28rUXpubWhMTTRBekJOZ05DZ3VOUnVNZllGTDNCOURFSTRUdzBxQU1NMQp2OXpIWUJBbEREZG85aldBZURKYVlzeGFvdC9IL2tLSC84NEQvT1ZvTUJuWGJWNUNCOWdSWXhhb1JZWjEwZklGCm1IUkpyV2pHK3g4NkJ1RDZRU2pVMGJOVGFnQmVqSzkrd2JMWUJHVHBEazVhd0VWaVk4a0NRbXduMmRsMFVmdWUKV0JCZmVXLzhWTWxINkhoc1kzdTFmSW42Y2lrMVFMTHVDVFpORStGK0UvSjZaV05DYWk4ZGZrVldydz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://f4f28f7e-ab62-47de-a234-f913a79c07e4.k8s.ondigitalocean.com
  name: do-nyc1-canabrava-devops
contexts:
- context:
    cluster: do-nyc1-canabrava-devops
    user: do-nyc1-canabrava-devops-admin
  name: do-nyc1-canabrava-devops
current-context: do-nyc1-canabrava-devops
users:
- name: do-nyc1-canabrava-devops-admin
  user:
